name: Sync SuzuBlog Main Branch 🐧✨

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0' # Run every Sunday at 00:00 UTC

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # Step 1: Checkout target repository
      - name: Checkout zla-pub main branch 🚀
        uses: actions/checkout@v4
        with:
          ref: main

      # Step 2: Check if running on main branch
      - name: Ensure running on main branch 🔍
        run: |
          CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
          echo "Current branch: $CURRENT_BRANCH"
          if [ "$CURRENT_BRANCH" != "main" ]; then
            echo "Not on main branch. Exiting."
            exit 1
          fi

      # Step 3: Clone SuzuBlog repository
      - name: Clone SuzuBlog repository 🌸
        run: |
          git clone --branch main --depth 1 https://github.com/ZL-Asica/SuzuBlog.git suzublog

      # Step 4: Sync content excluding specific paths
      - name: Sync content excluding specific paths ✨
        run: |
          rsync -av --delete \
            --exclude=".git/**" \
            --exclude="config.yml" \
            --exclude="src/app/robots.ts" \
            --exclude="posts/**" \
            --exclude="public/**" \
            --exclude="/.github/workflows/sync-suzublog.yml" \
            --exclude="suzublog/**" \
            suzublog/ .

      # Step 5: Delete temporary files
      - name: Clean up temporary files 🧹
        run: |
          rm -rf suzublog

      # Step 6: Detect changes and commit
      - name: Commit and push changes 📝
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Check for changes
          if [ -n "$(git status --porcelain)" ]; then
            echo "Changes detected, committing..."
            git add .
            git commit -m "✨ Synced with SuzuBlog main branch"
            git push origin main
          else
            echo "No changes detected. ✅"
          fi
